name: Deploy to Render

on:
  push:
    branches:
      - main  # deploy only when main branch updates

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          if [ -f package.json ]; then
            npm install
          fi

      - name: Run build (if any)
        run: |
          if [ -f package.json ]; then
            npm run build || echo "No build step"
          fi

      - name: Deploy to Render
        uses: render-examples/deploy-action@v1
        with:
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}
